### ISSUE TITLE
Error rlp: end of list on most blocks

### ISSUE THREAD

**Issue by tholcman** [48Club/bsc-snapshots#104]
Hi, 
we have started Erigon Mainnet Archive from the latest snapshot and we are getting error  "rlp: end of list"

```
$ erigon --version
erigon version 1.1.9-dev-4b352f69
```

```
curl --location 'http://127.0.0.1:7003' --header 'Content-Type: application/json' --data '{
    "method":"eth_getBlockByNumber",
    "params":[
        "29000000", true
        ],
    "id":1,
    "jsonrpc":"2.0"
}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"rlp: end of list"}}
```

we have tried few blocks and below 3,000,000 and on 30,000,000 and above it works but 4M-29M doesn't work with the error above.

**Comment by du5** [comment]
https://github.com/ethereum/go-ethereum/blob/master/rlp/decode.go

Please ask bsc or erigon developers where the problem lies, thanks

**Comment by tholcman** [comment]
Hi,
we have figured out that if you use only the DB snapshot, not the torrent, it doesn't work. When you leave the synchronization of torrent files on Erigon itself it is not possible to run the node, not even from scratch. Later we will probably create a ticket in bsc-erigon repo. For now your DB-Snapshot + Torrent Snapshot is the only way to start BSC Erigon Archive. Just please update FAQ + maybe add a note to README.md that you have to use both.

**Comment by du5** [comment]
After many tests, I determined that the seed file in bsc-erigon is damaged and it is currently unable to synchronize from the genesis block.
