### ISSUE TITLE
Error with archive extracting

### ISSUE THREAD

**Issue by fermanentdev** [48Club/bsc-snapshots#108]
Download action: axel -n 8 LINK
Downloaded file extension: .tar.zst

Extracting command: tar --zstd -xvf archive_name
Error:
/*stdin*\ : Decoding error (36) : Corrupted block detected
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

After the download finished, I didn't see any error messages from axel

**Comment by du5** [comment]
verify checksum & RTFM
