### ISSUE TITLE
Why is the full node snapshot for version 1.3.0 if it is still in pre-release state?

### ISSUE THREAD

**Issue by BuTema** [48Club/bsc-snapshots#109]
I'm trying to run the full version of node, but the latest version of geth is 1.2.12 and snapshot is only possible for version 1.3.0

**Comment by du5** [comment]
The code has been merged into the bsc master branch.

If more people use the beta version, the testing process can be completed faster and code bugs can be eliminated and resolved faster.

**Comment by tardigralice** [comment]
i have same problem.

1.3.0 is not compatible with "on critical business" as it's noted on the release page.
and i had several crash.

please provide snapshot with 1.2.12
thanks !
