### ISSUE TITLE
snapshot not working with official latest BSC geth version (1.12.2)

### ISSUE THREAD

**Issue by tardigralice** [48Club/bsc-snapshots#110]
BSC geth officialy rolled back to 1.2.12 because of 1.3 instability. (1.3 is considered as now as a pre-release)

Can you do the snapshot with 1.2.12 ? because actual snapshot not work with 1.2.12

thanks

**Comment by du5** [comment]
https://github.com/48Club/bsc-snapshots/tree/b6ce2b4d2393eb01a3650196034502517de89d06

**Comment by extradz** [comment]
link above not working for fast node
