### ISSUE TITLE
能不能搞一个1.2.13能用的版本啊

### ISSUE THREAD

**Issue by a5868519** [48Club/bsc-snapshots#113]
能不能搞一个1.2.13能用的版本啊新的这个咔咔报错呢

**Comment by ifsayyes** [comment]
对呀，升级了1.3.0的fullnode之后，
根本就无法启动 geth1.2.13，一启动就立马exit
我也无法退版fullnode...无奈只能用 geth1.3.0…
![image](https://github.com/48Club/bsc-snapshots/assets/135924607/6de62037-267d-4e35-983d-bc66f9c842f4)
![image](https://github.com/48Club/bsc-snapshots/assets/135924607/bddebedd-02de-42d2-ab39-3d06654181a8)

**Comment by ifsayyes** [comment]
> 能不能搞一个1.2.13能用的版本啊新的这个咔咔报错呢

哥，试一下这个快照node
Snapshot: https://github.com/bnb-chain/bsc-snapshots#endpoint

**Comment by lmcapp** [comment]
> 对呀，升级了1.3.0的fastnode之后， 根本就无法启动 geth1.2.13，一启动就立马exit 也没有其他选择可以降版fastnode鸭。。。...无奈只能用 geth1.3.0… ![image](https://user-images.githubusercontent.com/135924607/281219125-efbbb13d-a51d-480d-9666-fa678c78d049.png)
> 
> ![image](https://user-images.githubusercontent.com/135924607/281218869-bddebedd-02de-42d2-ab39-3d06654181a8.png)
我用1.3.0的geth 也启动不了 报错：Fatal: Could not open database: open  usr/bsc/node/geth/chaindata/ancient/chain/headers.cidx: no such file or directory

**Comment by du5** [comment]
1.3 添加启动参数了吗？看看 readme

**Comment by lmcapp** [comment]
> 1.3 添加启动参数了吗？看看readme
加了这个 --db.engine=pebble，可以了。。。
