### ISSUE TITLE
snapshot for fastnode not working with official latest BSC geth version (1.12.2)

### ISSUE THREAD

**Issue by extradz** [48Club/bsc-snapshots#114]
BSC geth officialy rolled back to 1.2.12 because of 1.3 instability. (1.3 is considered as now as a pre-release)

Can you do the snapshot with 1.2.12 ? because actual snapshot not work with 1.2.12

i saw the msg from another dev, but the link not work

https://github.com/48Club/bsc-snapshots/tree/b6ce2b4d2393eb01a3650196034502517de89d06

**Comment by ifsayyes** [comment]
> BSC geth officialy rolled back to 1.2.12 because of 1.3 instability. (1.3 is considered as now as a pre-release)
> 
> Can you do the snapshot with 1.2.12 ? because actual snapshot not work with 1.2.12
> 
> i saw the msg from another dev, but the link not work
> 
> https://github.com/48Club/bsc-snapshots/tree/b6ce2b4d2393eb01a3650196034502517de89d06



Thy this snapshot: https://github.com/bnb-chain/bsc-snapshots#endpoint

**Comment by lmcapp** [comment]
> > BSC geth officialy rolled back to 1.2.12 because of 1.3 instability. (1.3 is considered as now as a pre-release)
> > Can you do the snapshot with 1.2.12 ? because actual snapshot not work with 1.2.12
> > i saw the msg from another dev, but the link not work
> > https://github.com/48Club/bsc-snapshots/tree/b6ce2b4d2393eb01a3650196034502517de89d06
> 
> Thy this snapshot: https://github.com/bnb-chain/bsc-snapshots#endpoint

This snapshots is too large!!!

**Comment by du5** [comment]
We believe that 1.3.0 will be merged into the mainline sooner or later, and it is a good practice to lay the groundwork for the new version first.

> https://github.com/48Club/bsc-snapshots/tree/b6ce2b4d2393eb01a3650196034502517de89d06

Looks like this snapshot has been cleaned up, sorry

**Comment by du5** [comment]
https://github.com/bnb-chain/bsc/pull/1986
