### ISSUE TITLE
how to use Geth fast node

### ISSUE THREAD

**Issue by huangzhengwang** [48Club/bsc-snapshots#124]
how to use Geth fast node，I only extracted over 60 GB of files and don't know how to use them

**Comment by huangzhengwang** [comment]
我也觉得奇怪，感觉像是解压一半就终中断了 但是也没有报错 tar -I zstd -xvf geth.fast.33660414.tar.zst

**Comment by huangzhengwang** [comment]
> 我也觉得奇怪，感觉解压一半就终止了，但是也没有报错 tar -I zstd -xvf geth.fast.33660414.tar.zst

看下了sha256不一样 估计下载有问题

**Comment by du5** [comment]
🤔️
