### ISSUE TITLE
最新的快照 无法跑起来，直接OOM

### ISSUE THREAD

**Issue by lichao1991** [48Club/bsc-snapshots#127]
System information
亚马逊服务器:用的官方配置的实例机型m5zn.3xl

Geth version: v1.2.15
OS & Version: ubuntu
Commit hash : (if develop)

用的快照
Version	[develop@8b94dd](https://github.com/bnb-chain/bsc/tree/8b94dd6b5929f26c24701ed5074b490e7d4e23ab)
Block	[33660414](https://bscscan.com/block/33660414) (Nov-20-2023 02:40:35 PM +UTC)

Expected behaviour
Actual behaviour
Steps to reproduce the behaviour
nohup /data/bsc/build/bin/geth_linux --config ./config.toml --datadir ./node --txlookuplimit=0 --syncmode=full --tries-verify-mode=none --pruneancient=true --cache 8000 &

Backtrace
INFO [12-04|16:09:09.233] Starting Geth on Ethereum mainnet...
INFO [12-04|16:09:09.235] Maximum peer count ETH=200 LES=0 total=200
INFO [12-04|16:09:09.235] Smartcard socket not found, disabling err="stat /run/pcscd/pcscd.comm: no such file or directory"
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x262c303?, 0x10000?})
/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/panic.go:1047 +0x5d fp=0x7fe9caa7b868 sp=0x7fe9caa7b838 pc=0x43b6fd
runtime.sysMapOS(0xc031800000, 0x59c8400000?)
/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/mem_linux.go:187 +0x11b fp=0x7fe9caa7b8b0 sp=0x7fe9caa7b868 pc=0x419efb
runtime.sysMap(0x4882620?, 0x7fe9f6312000?, 0x42f380?)
/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/mem.go:142 +0x35 fp=0x7fe9caa7b8e0 sp=0x7fe9caa7b8b0 pc=0x4198d5
runtime.(*mheap).grow(0x4882620, 0x2ce40a8?)
/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/mheap.go:1468 +0x23d fp=0x7fe9caa7b950 sp=0x7fe9caa7b8e0 pc=0x42c37d
runtime.(*mheap).allocSpan(0x4882620, 0x2ce40a8, 0x0, 0x1)
/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/mheap.go:1199 +0x1be fp=0x7fe9caa7b9e8 sp=0x7fe9caa7b950 pc=0x42babe
runtime.(*mheap).alloc.func1()
/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/mheap.go:918 +0x65 fp=0x7fe9caa7ba30 sp=0x7fe9caa7b9e8 pc=0x42b545
runtime.systemstack()
/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/asm_amd64.s:492 +0x49 fp=0x7fe9caa7ba38 sp=0x7fe9caa7ba30 pc=0x46e169

**Comment by lichao1991** [comment]
> 你没有遵守使用特定版本 <img alt="image" width="239" src="https://private-user-images.githubusercontent.com/54979375/287946512-81c18010-f8a2-40d6-a6ed-40c7236fb459.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTg2MDgsIm5iZiI6MTcwMTc1ODMwOCwicGF0aCI6Ii81NDk3OTM3NS8yODc5NDY1MTItODFjMTgwMTAtZjhhMi00MGQ2LWE2ZWQtNDBjNzIzNmZiNDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA2MzgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOGYzMDQ2NDE5NGJkNGY0NTZiN2ViMzJmNjBiZjFhMmI3MjE3OWM5Zjk3M2ZiZDY2ZDAxNzYyYzg5NDFlZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHsPwWgdrBDJZOyETX_-QKzaZ9HYuJjehUzcyAmvwoQ">



> 你没有遵守使用特定版本 <img alt="image" width="239" src="https://private-user-images.githubusercontent.com/54979375/287946512-81c18010-f8a2-40d6-a6ed-40c7236fb459.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTg2MDgsIm5iZiI6MTcwMTc1ODMwOCwicGF0aCI6Ii81NDk3OTM3NS8yODc5NDY1MTItODFjMTgwMTAtZjhhMi00MGQ2LWE2ZWQtNDBjNzIzNmZiNDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA2MzgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOGYzMDQ2NDE5NGJkNGY0NTZiN2ViMzJmNjBiZjFhMmI3MjE3OWM5Zjk3M2ZiZDY2ZDAxNzYyYzg5NDFlZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHsPwWgdrBDJZOyETX_-QKzaZ9HYuJjehUzcyAmvwoQ">

这个版本是 1.3.0 吗？

**Comment by du5** [comment]
用最新1.3.4 就可以

**Comment by lichao1991** [comment]
> 用最新1.3.4 就可以

嗯 可以了
