### ISSUE TITLE
Missing block in the middle, aiming genesis number=35,086,500

### ISSUE THREAD

**Issue by B1Q** [48Club/bsc-snapshots#133]
Fresh snapshot extracted and I'm still getting this 

WARN [01-13|12:51:28.508] Head state missing, repairing            number=35,176,500 hash=a83303..ec1935 diskRoot=ea501a..7d05af
ERROR[01-13|12:52:02.881] Missing block in the middle, aiming genesis number=35,086,500 hash=ecbee9..be63ab
INFO [01-13|12:52:02.881] Reset to block with genesis state        number=0          hash=0d2184..d57b5b
INFO [01-13|12:52:02.881] Rewound to block with state              number=0          hash=0d2184..d57b5b

**Comment by du5** [comment]
It looks like you haven't updated to the latest version of geth


This should be caused by the hard fork being highly unavailable.

**Comment by B1Q** [comment]
> It looks like you haven't updated to the latest version of geth
> 
> This should be caused by the hard fork being highly unavailable.

I am on 1.3.7

**Comment by du5** [comment]
> I am on 1.3.7

I can't reproduce this problem
