### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by SECTOR-1** [48Club/bsc-snapshots#136]
i used the:
![image](https://github.com/48Club/bsc-snapshots/assets/94073451/10e8227d-2c27-4f24-86bb-6f20fe972000)

start to sync and got this error:

panic: runtime error: invalid memory address or nil pointer dereference
Jan 25 20:40:23 orangepi5 bash[193409]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbc4664]
Jan 25 20:40:23 orangepi5 bash[193409]: goroutine 1 [running]:
Jan 25 20:40:23 orangepi5 bash[193409]: github.com/ethereum/go-ethereum/core/rawdb.(*ResettableFreezer).AncientRange(0x40017b2000?, {0x25a47b7?, 0x4011ae8e20?}, 0x4000479a08?, 0x4000479b08?, 0x214da80?)
Jan 25 20:40:23 orangepi5 bash[193409]:         /home/runner/work/bsc/bsc/core/rawdb/freezer_resettable.go:125 +0x34
Jan 25 20:40:23 orangepi5 bash[193409]: github.com/ethereum/go-ethereum/core/rawdb.ReadStateHistoryMetaList(...)
Jan 25 20:40:23 orangepi5 bash[193409]:         /home/runner/work/bsc/bsc/core/rawdb/accessors_state.go:180
Jan 25 20:40:23 orangepi5 bash[193409]: github.com/ethereum/go-ethereum/trie/triedb/pathdb.checkHistories(0x0, 0xdfacbb468a60fb71?, 0xc9c7e760d93b58c2?, 0x40147b7728)
Jan 25 20:40:23 orangepi5 bash[193409]:         /home/runner/work/bsc/bsc/trie/triedb/pathdb/history.go:548 +0x70

**Comment by du5** [comment]
This bug in geth has been fixed by the bsc team and will be applied in version 1.3.8. This is not a snapshot problem.

**Comment by SECTOR-1** [comment]
thanks :-)
