### ISSUE TITLE
No such file or directory (database)

### ISSUE THREAD

**Issue by fermanentdev** [48Club/bsc-snapshots#137]
I did:

aria2c ... https://snapshots.48.club/geth.fast.35407303.tar.zst -o geth.tar.lz4
zstd -cd geth.tar.lz4 | tar xf -
sha256 geth.tar.lz4 and sha256 on github is equal

I run:
./geth_linux --tries-verify-mode none --config ~/bsc/config.toml --datadir ~/bsc --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

Then i got:
Fatal: Could not open database: open /root/bsc/chaindata/ancient/chain/diffs.ridx: no such file or directory

**Comment by du5** [comment]
readme first
