### ISSUE TITLE
Snapshots file don't have triecache in geth folder 

### ISSUE THREAD

**Issue by supamongkonR** [48Club/bsc-snapshots#140]
After extract snapshot file that I've to down load from https://github.com/48Club/bsc-snapshots
file - https://snapshots.48.club/geth.full.36503935.tar.zst 

and then what I got after extract file is just ```chaindata``` folder inside ```geth```, it should be have ```triecache``` like the full snapshot that I was download in previously,  here https://github.com/bnb-chain/bsc-snapshots right ? 

my question is when finish extract snapshot and got just ```chaindata```, so i can stat node like normally even there's is no ```triecache```  folder or not ? 
cause from documentation of BNB they suggest to move 2 folder from snapshot folder to oust side and point geth fag command data to start node 
```sh
mv server/data-seed/geth/chaindata node/geth/chaindata
mv server/data-seed/geth/triecache node/geth/triecache
```
but right now after extract file I don't get ```triecache``` 

so then i need to handle just 
```sh
mv server/data-seed/geth/chaindata node/geth/chaindata
```

and then start node or which one that I can do ?, Please someone explain me.

Thanks you so much.

**Comment by du5** [comment]
It is recommended that you directly point --datadir to the decompressed directory, which is similar to `$PWD/geth.full`. Those files are unnecessary. Please read the readme for startup parameters.

**Comment by supamongkonR** [comment]
Thanks for reply
I just wonder why after extract file we don't get ```triecache``` like download from https://github.com/bnb-chain/bsc-snapshots or this is the reason that snapshot from 48 club has minimum size than from bsc-snapshot ?

**Comment by du5** [comment]
The small size is because I prune the database, triecache is just cache, and its size is insignificant.
