### ISSUE TITLE
https://snapshots.48.club/geth.fast.36791277.tar.zst  404

### ISSUE THREAD

**Issue by c1dx** [48Club/bsc-snapshots#142]
https://snapshots.48.club/geth.fast.36791277.tar.zst  404

**Comment by du5** [comment]
99eab9e1dc5ff9e735d5599564d27a8b20e78e1c

**Comment by AlexsdeG** [comment]
same https://snapshots.48.club/geth.fast.36791277.tar.zst 404
but both full node snapshot links are working perfectly fine
