### ISSUE TITLE
是否更新，1.4.5版本相关的快照

### ISSUE THREAD

**Issue by yaocccc** [48Club/bsc-snapshots#150]
目前已更新1.4.5版本的geth，我发现新部署的机器总是会卡在

> eth.syncing
{
  currentBlock: 38141209,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 38136543,
  startingBlock: 37731483,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0,
  txIndexFinishedBlocks: 4538845,
  txIndexRemainingBlocks: 33602365
}

txIndexFinishedBlocks 不会追平，期望早更新新的快照，我想用新的快照试试看

**Comment by du5** [comment]
理论上软件会向下兼容, 这个问题建议反馈给 bsc 团队,

**Comment by zhk101** [comment]
@yaocccc did you get around this issue? I'm experiencing the same thing.
