### ISSUE TITLE
Synchronisation failed, retrying

### ISSUE THREAD

**Issue by hljie** [48Club/bsc-snapshots#151]
`
t=2024-05-08T13:07:11+0000 lvl=info msg="New local node record" seq=1715172369839 id=360083088d51723f5434a62040fe789b23ea1e8b93639605979b08b933e71927 ip=18.232.163.227 udp=30311 tcp=30311
t=2024-05-08T13:07:13+0000 lvl=info msg="Block synchronisation started"                                                 t=2024-05-08T13:07:13+0000 lvl=warn msg="Multiple headers for single request" peer=915bb84f headers=0                   t=2024-05-08T13:07:13+0000 lvl=warn msg="Synchronisation failed, dropping peer" peer=915bb84ff81d3c841622673416b60f0195bdfada8ca8e162afb0152a8d336cfc err="action from bad peer ignored: multiple headers (0) for single request"               t=2024-05-08T13:07:13+0000 lvl=warn msg="Synchronisation failed, retrying" peer=915bb84ff81d3c841622673416b60f0195bdfada8ca8e162afb0152a8d336cfc err="peer is unknown or unhealthy"                                                             t=2024-05-08T13:07:17+0000 lvl=warn msg="Multiple headers for single request" peer=013cebe6 headers=0                   t=2024-05-08T13:07:17+0000 lvl=warn msg="Synchronisation failed, dropping peer" peer=013cebe6cf66d817fb4b7779a3918620616f98e0717dfe2f68fec8492c78d9da err="action from bad peer ignored: multiple headers (0) for single request"               t=2024-05-08T13:07:17+0000 lvl=warn msg="Synchronisation failed, retrying" peer=013cebe6cf66d817fb4b7779a3918620616f98e0717dfe2f68fec8492c78d9da err="peer is unknown or unhealthy"                                                             t=2024-05-08T13:07:17+0000 lvl=warn msg="Synchronisation failed, retrying" peer=013cebe6cf66d817fb4b7779a3918620616f98e0717dfe2f68fec8492c78d9da err="peer is unknown or unhealthy"                                                             t=2024-05-08T13:07:17+0000 lvl=warn msg="Synchronisation failed, retrying" peer=013cebe6cf66d817fb4b7779a3918620616f98e0717dfe2f68fec8492c78d9da err="peer is unknown or unhealthy"                                                             t=2024-05-08T13:07:17+0000 lvl=warn msg="Synchronisation failed, retrying" peer=013cebe6cf66d817fb4b7779a3918620616f98e0717dfe2f68fec8492c78d9da err="peer is unknown or unhealthy"                                                             t=2024-05-08T13:07:17+0000 lvl=warn msg="Synchronisation failed, retrying" peer=013cebe6cf66d817fb4b7779a3918620616f98e0717dfe2f68fec8492c78d9da err="peer is unknown or unhealthy"
t=2024-05-08T13:07:17+0000 lvl=warn msg="Synchronisation failed, retrying" peer=013cebe6cf66d817fb4b7779a3918620616f98e0717dfe2f68fec8492c78d9da err="peer is unknown or unhealthy"
t=2024-05-08T13:07:17+0000 lvl=warn msg="Synchronisation failed, retrying" peer=013cebe6cf66d817fb4b7779a3918620616f98e0717dfe2f68fec8492c78d9da err="peer is unknown or unhealthy"                                                             t=2024-05-08T13:07:19+0000 lvl=warn msg="Ancestor below allowance" peer=017a54a6 number=38383323 hash=0x0000000000000000000000000000000000000000000000000000000000000000 allowance=38383323                                                     t=2024-05-08T13:07:19+0000 lvl=warn msg="Synchronisation failed, dropping peer" peer=017a54a614b1f169880968c60fe5a6d6e2f836c27e4eaf5c13795e75806ee5bd err="retrieved ancestor is invalid"                                                       t=2024-05-08T13:07:19+0000 lvl=warn msg="Synchronisation failed, retrying" peer=017a54a614b1f169880968c60fe5a6d6e2f836c27e4eaf5c13795e75806ee5bd err="peer is unknown or unhealthy"                                                             t=2024-05-08T13:07:19+0000 lvl=warn msg="Synchronisation failed, retrying" peer=017a54a614b1f169880968c60fe5a6d6e2f836c27e4eaf5c13795e75806ee5bd err="peer is unknown or unhealthy"
`
what causes the error, and how to deal? I deploy fast node on aws, thank you

**Comment by du5** [comment]
https://github.com/bnb-chain/bsc/issues/2437

**Comment by du5** [comment]
65785a20c49af64f14e437f6f63f7641ff7e1651

**Comment by du5** [comment]
Redownload historical snapshots

**Comment by hljie** [comment]
I will try to redownload, but the version I used when I submit the issue also show the errors: Number of finalized block is missing

`t=2024-05-08T14:18:58+0000 lvl=warn msg="Synchronisation failed, retrying" peer=8cd901361539a489dfa966b32d35a4fc68036262f240e0890eb02e284abe1ed1 err="peer is unknown or unhealthy"
t=2024-05-08T14:19:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:20:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:21:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:22:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:23:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:24:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:25:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:26:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:27:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:27:23+0000 lvl=warn msg="Served eth_coinbase" conn=172.31.41.162:47942 reqid=3 t=15.875µs err="etherbase must be explicitly specified" X-Forwarded-For=<nil>
t=2024-05-08T14:27:23+0000 lvl=warn msg="Served eth_coinbase" conn=172.31.41.162:47942 reqid=3 duration=14.876µs err="etherbase must be explicitly specified"
t=2024-05-08T14:28:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:29:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:30:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:31:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:32:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:33:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:34:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:35:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:36:10+0000 lvl=error msg="Number of finalized block is missing"
t=2024-05-08T14:37:10+0000 lvl=error msg="Number of finalized block is missi`

**Comment by du5** [comment]
What I mean is downloading the 38198925 snapshot, not re-downloading the latest snapshot

**Comment by hljie** [comment]
yes，I use v1.4.5 now and it worked normally for two hours ，but I get a error：
`Fatal: Failed to register the Ethereum service: state is not available`
could you please help me，thank you

**Comment by hljie** [comment]
> What I mean is downloading the 38198925 snapshot, not re-downloading the latest snapshot

oh，yes，I changed
