### ISSUE TITLE
currentBlock is higher than highestBlock. 

### ISSUE THREAD

**Issue by daron4ever** [48Club/bsc-snapshots#152]
![Screenshot 2024-05-15 at 9 46 14 PM](https://github.com/48Club/bsc-snapshots/assets/18229512/a87af7a9-fb83-47f6-9d62-4a6bef83838a)

What is the happening?
I downloaded  v1.4.5 full node and currentBlock is always higher than highestBlock.

**Comment by zhk101** [comment]
Try changing `--history.transactions=0` to `--history.transactions=90000`

**Comment by du5** [comment]
link to https://github.com/bnb-chain/bsc/issues/2436

**Comment by daron4ever** [comment]
Thanks. it worked after i changed to --history.transactions=90000
