### ISSUE TITLE
geth.pbss.39422280.tar.zst 使用出现异常无法更新，请问什么时候会有新的快照

### ISSUE THREAD

**Issue by seb-zhu** [48Club/bsc-snapshots#159]
geth.pbss.39422280.tar.zst 使用出现异常无法更新，请问什么时候会有新的快照
非常感谢

**Comment by du5** [comment]
什么异常

**Comment by seb-zhu** [comment]
嗯，我重新解压快照，重新开始，尝试后已经可以，不过因为太久远了，目前同步比较慢。
烦请关闭问题，是我这边问题
