### ISSUE TITLE
Full node issue

### ISSUE THREAD

**Issue by TehnobitSystems** [48Club/bsc-snapshots#163]
Hello. https://snapshots.48.club/geth.full.42568228.tar.zst 
Error 404
Object not found

**Comment by du5** [comment]
https://snapshots.48.club/geth.full.42451514.tar.zst

Download old snapshots

**Comment by kelaile** [comment]
INFO [09-28|11:32:47.469] Looking for peers                        peercount=1 tried=102 static=0
WARN [09-28|11:32:50.115] Multiple headers for single request      peer=8bc9a289 headers=0
WARN [09-28|11:32:50.115] Synchronisation failed, dropping peer    peer=8bc9a2890fcfa9ce28b454856456e50ba30b2522eab2aced84945d2268d5b487 err="action from bad peer ignored: multiple headers (0) for single request"
INFO [09-28|11:32:57.530] Looking for peers                        peercount=0 tried=66  static=0
INFO [09-28|11:33:00.774] Syncing: state healing in progress       accounts=10847@598.87KiB slots=32463@2.67MiB   codes=697@5.07MiB nodes=18,365,696@5.21GiB pending=1
ERROR[09-28|11:33:00.882] Error importing chain data to ancients   err="can't add block 1 hash: the append operation is out-order: have 1 want 42271249"
INFO [09-28|11:33:00.892] Syncing: state healing in progress       accounts=10847@598.87KiB slots=32463@2.67MiB   codes=697@5.07MiB nodes=18,365,969@5.21GiB pending=4369
WARN [09-28|11:33:00.895] Rewinding blockchain to block            target=0
WARN [09-28|11:33:00.958] Unexpected trienode heal packet          peer=d4647a49 reqid=1,110,231,066,231,619,192
INFO [09-28|11:33:00.972] Reset to block with genesis state        number=0          hash=0d2184..d57b5b
INFO [09-28|11:33:00.972] Rewound to block with state              number=0          hash=0d2184..d57b5b
INFO [09-28|11:33:00.975] Loaded most recent local block           number=0          hash=0d2184..d57b5b root=919fcc..03b422 td=1          age=4y6mo1d
INFO [09-28|11:33:00.975] Loaded most recent local finalized block number=0          hash=0d2184..d57b5b root=919fcc..03b422 td=1          age=4y6mo1d
INFO [09-28|11:33:00.975] Loaded last snap-sync pivot marker       number=23,845,936
WARN [09-28|11:33:00.975] Rolled back chain segment                header=384->0       snap=0->0 block=0->0 reason="syncing canceled (requested)"
WARN [09-28|11:33:00.975] Synchronisation failed, dropping peer    peer=d4647a49e2ef3d7b335b3d4da882411e1f40a5a09381cf2f72afe50deffc8dfb err="retrieved hash chain is invalid: can't add block 1 hash: the append operation is out-order: have 1 want 42271249"
WARN [09-28|11:33:06.426] Snapshot extension registration failed   peer=d03cbc10 err="peer connected on snap without compatible eth support"
INFO [09-28|11:33:07.715] Looking for peers                        peercount=1 tried=71  static=0
INFO [09-28|11:33:11.817] Syncing: state healing in progress       accounts=10847@598.87KiB slots=32463@2.67MiB   codes=697@5.07MiB nodes=18,365,969@5.21GiB pending=1
ERROR[09-28|11:33:11.982] Error importing chain data to ancients   err="can't add block 1 hash: the append operation is out-order: have 1 want 42271249"
INFO [09-28|11:33:11.982] Syncing: state healing in progress       accounts=10847@598.87KiB slots=32463@2.67MiB   codes=697@5.07MiB nodes=18,365,969@5.21GiB pending=1
WARN [09-28|11:33:11.985] Rewinding blockchain to block            target=0
INFO [09-28|11:33:12.061] Reset to block with genesis state        number=0          hash=0d2184..d57b5b
INFO [09-28|11:33:12.061] Rewound to block with state              number=0          hash=0d2184..d57b5b
INFO [09-28|11:33:12.063] Loaded most recent local block           number=0          hash=0d2184..d57b5b root=919fcc..03b422 td=1          age=4y6mo1d
INFO [09-28|11:33:12.063] Loaded most recent local finalized block number=0          hash=0d2184..d57b5b root=919fcc..03b422 td=1          age=4y6mo1d
INFO [09-28|11:33:12.063] Loaded last snap-sync pivot marker       number=30,720,031
WARN [09-28|11:33:12.063] Rolled back chain segment                header=384->0       snap=0->0 block=0->0 reason="syncing canceled (requested)"
WARN [09-28|11:33:12.063] Synchronisation failed, dropping peer    peer=d0394667da7ffd6870ba52d6ab86803a5c57e11ec2b069558026372fa90b1875 err="retrieved hash chain is invalid: can't add block 1 hash: the append operation is out-order: have 1 want 42271249"
INFO [09-28|11:33:17.818] Looking for peers                        peercount=0 tried=47  static=0


What's wrong with the snapshot?
