### ISSUE TITLE
最新的全节点快照出现一个错误

### ISSUE THREAD

**Issue by kelaile** [48Club/bsc-snapshots#167]
最新的全节点快照出现一个错误-导致节点无法启动
ERROR[09-28|21:56:51.591] Invalid block header RLP                 hash=0925dd..64f334 err="rlp: input list has too many elements for types.Header"
Fatal: Failed to register the Ethereum service: missing head header

**Comment by du5** [comment]
无法复现

**Comment by kelaile** [comment]
现在只能等待你们再次更新full node 快照了

**Comment by du5** [comment]
快照没有问题，无法复现你的问题

**Comment by kelaile** [comment]
请问这是什么原因？我从创世块是可以同步的，使用快照就不可以了

**Comment by du5** [comment]
与快照数据本身无关的错误, 请反馈给 bsc
