### ISSUE TITLE
FAST节点快照错误

### ISSUE THREAD

**Issue by oyl826** [48Club/bsc-snapshots#168]
geth --config ./config.toml --datadir ./node  --cache 51200 --rpc.allow-unprotected-txs --history.transactions=90000 --syncmode=full --db.engine=pebble --tries-verify-mode=none

错误提示：Failed to register the Ethereum service: db.engine choice was pebble but found pre-existing leveldb database in specified data directory

**Comment by du5** [comment]
与快照无关的错误, 请反馈给 bsc
