### ISSUE TITLE
Snapshot corrupted

### ISSUE THREAD

**Issue by chevoisiatesalvati** [48Club/bsc-snapshots#44]
I tried more than once but this snapshot seems not working.
Node started to sync from genesis, so I stopped it and restarted and now it seems not syncing at all.
Between multiples bad peer errors there's this one that I never saw before and I don't know if it should be there: "retrieved hash chain is invalid: missing parent"

**Comment by du5** [comment]
Please ensure that the file characteristics after downloading are consistent

There is no problem with the snapshot itself
