### ISSUE TITLE
The last snapshot is created 12 days ago

### ISSUE THREAD

**Issue by tiendo1011** [48Club/bsc-snapshots#46]
The readme mentions that there will be a new snapshot every 36 hours, but the last snapshot is created 12 days ago

**Comment by du5** [comment]
Suspension of snapshots is by internal vote, I can not disclose the reason

The good news is that the packaging process has restarted.

**Comment by du5** [comment]
A new snapshot will be published in about 48 hours at the slowest.

**Comment by du5** [comment]
A new snapshot has been released
