### ISSUE TITLE
Increase  prune.h.older value

### ISSUE THREAD

**Issue by zhy827827** [48Club/bsc-snapshots#47]
erigon  --chain=bsc --prune=hrtc   default --prune.h.older=90000,But I want to increase the value of prune.h.older，

Error: not allowed change of --prune flag
EROR[01-03|10:00:57.816] Erigon startup                           err="not allowed change of --prune flag, last time you used: --prune.h.older=90000 --prune.r.older=90000 --prune.t.older=90000 --prune.c.older=90000"

How Do I set it up?

**Comment by du5** [comment]
u can't
