### ISSUE TITLE
Please UPDATE snapshot THANKS ! 

### ISSUE THREAD

**Issue by zhy827827** [48Club/bsc-snapshots#52]
!!! from block [25699883](https://bscscan.com/block/25699883)  can not download!!!

**Comment by zhy827827** [comment]
02/16 10:40:32 [ERROR] CUID#9 - Download aborted. URI=https://snapshots.48.club/erigon.25699883.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://snapshots.48.club/erigon.25699883.tar.lz4
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

02/16 10:40:32 [ERROR] CUID#14 - Download aborted. URI=https://snapshots.48.club/erigon.25699883.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://snapshots.48.club/erigon.25699883.tar.lz4
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

02/16 10:40:32 [ERROR] CUID#19 - Download aborted. URI=https://snapshots.48.club/erigon.25699883.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://snapshots.48.club/erigon.25699883.tar.lz4
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

02/16 10:40:32 [ERROR] CUID#21 - Download aborted. URI=https://snapshots.48.club/erigon.25699883.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://snapshots.48.club/erigon.25699883.tar.lz4
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

02/16 10:40:32 [ERROR] CUID#20 - Download aborted. URI=https://snapshots.48.club/erigon.25699883.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://snapshots.48.club/erigon.25699883.tar.lz4
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403
 *** Download Progress Summary as of Thu Feb 16 10:41:32 2023 ***

**Comment by du5** [comment]
Your ip address is in the cloudflare blacklist and has nothing to do with snapshots

**Comment by zhy827827** [comment]
???  cloudflare  blacklist!!

**Comment by du5** [comment]
Please google yourself http code 403

**Comment by zhy827827** [comment]
root@gateway-ca-01:/mnt# aria2c -s14 -x14 -k100M https://snapshots.48.club/erigon.25785191.tar.lz4

02/21 07:25:39 [NOTICE] Downloading 1 item(s)

02/21 07:25:39 [ERROR] CUID#7 - Download aborted. URI=https://snapshots.48.club/erigon.25785191.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://snapshots.48.club/erigon.25785191.tar.lz4
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

02/21 07:25:39 [NOTICE] Download GID#b0375b2613f7c490 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
b0375b|ERR |       0B/s|https://snapshots.48.club/erigon.25785191.tar.lz4

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Comment by zhy827827** [comment]
I downloaded the snapshot for 2 weeks but didn't download it. I changed three servers, Can you solve this problem?If you can't solve it, tell the BSC official that you can't serve the community！
