### ISSUE TITLE
Cannot download snapshot！！！

### ISSUE THREAD

**Issue by zhy827827** [48Club/bsc-snapshots#53]
**I have downloaded snapshots for two weeks，But I still haven't downloaded the snapshot。I changed 5 servers to download！！！！

Can you fix this or not?**

02/22 04:23:27 [ERROR] CUID#17 - Download aborted. URI=https://snapshots.48.club/erigon.25828438.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://snapshots.48.club/erigon.25828438.tar.lz4
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

02/22 04:23:27 [ERROR] CUID#18 - Download aborted. URI=https://snapshots.48.club/erigon.25828438.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://snapshots.48.club/erigon.25828438.tar.lz4
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

02/22 04:23:27 [ERROR] CUID#19 - Download aborted. URI=https://snapshots.48.club/erigon.25828438.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://snapshots.48.club/erigon.25828438.tar.lz4
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

02/22 04:23:27 [ERROR] CUID#20 - Download aborted. URI=https://snapshots.48.club/erigon.25828438.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://snapshots.48.club/erigon.25828438.tar.lz4
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

02/22 04:23:27 [ERROR] CUID#21 - Download aborted. URI=https://snapshots.48.club/erigon.25828438.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://snapshots.48.club/erigon.25828438.tar.lz4
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

02/22 04:23:27 [NOTICE] Download GID#a845ab9bfc7f11f3 not complete: /mnt/erigon.25828438.tar.lz4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
a845ab|ERR |       0B/s|/mnt/erigon.25828438.tar.lz4

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
root@gateway-ca-01:/mnt# aria2c -s14 -x14 -k100M https://snapshots.48.club/erigon.25828438.tar.lz4

**Comment by du5** [comment]
redirect to https://github.com/aria2/aria2/issues?q=is%3Aissue+is%3Aopen+403
