### ISSUE TITLE
aria2c下载每次剩下最后一点就出错

### ISSUE THREAD

**Issue by lusiwei** [48Club/bsc-snapshots#59]
<img width="972" alt="截屏2023-04-04 20 20 47" src="https://user-images.githubusercontent.com/32103164/229789783-6a51c57c-983c-4518-a105-cc0d6a34d92b.png">

第一次出错，删了重新下载，第二次还是这样，是不是下载服务器有什么限制，每次剩下10分钟左右就下载完了就出错

**Comment by du5** [comment]
403 http 代码是拒绝服务，是 cloudflare 返回的 建议减少 aria 线程数量
