### ISSUE TITLE
snapshot pause

### ISSUE THREAD

**Issue by du5** [48Club/bsc-snapshots#63]
old server expired, We purchased new servers, our server orders are still queued due to too many Hetzner orders

<img width="492" alt="image" src="https://github.com/48Club/bsc-snapshots/assets/54979375/55140c80-15bb-46c5-8959-fcc92689a319">

**Comment by arialix** [comment]
Hi, waiting for your new magic snapshot :), my node can't go over block 29020050... 
Try to resync with your last snapshot, but error on the same block, maybe you know how to solve that without waiting snapshot?


t=2023-06-14T10:23:50+0000 lvl=warn msg="Synchronisation failed, retrying"       peer=a3377f4a2b73ea33ec9ce9b3bd0971d44353667df1aab0f0fe04cac7aaba403b err="peer is unknown or unhealthy"
t=2023-06-14T10:23:50+0000 lvl=eror msg="Expired request does not exist"         peer=3f99bc328600bd4f84c82b6f4630130b922bc397ec360abc466211a58b3ce40a
t=2023-06-14T10:23:50+0000 lvl=eror msg="Pending request exists for joining peer" peer=944df2bf
t=2023-06-14T10:23:52+0000 lvl=eror msg="validate state failed"                  error="invalid gas used (remote: 11928203 local: 11928058)"
t=2023-06-14T10:23:52+0000 lvl=info msg="Skip duplicated bad block"              number=29,020,050 hash=0x975da225aa3b6b89d5640dc952b8c0a691471def59592c135d244ea6e741b400
t=2023-06-14T10:23:52+0000 lvl=eror msg="\n########## BAD BLOCK #########\nChain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, CatalystBlock: <nil>, London: <nil>, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Gibbs: 23846001, Nano: 21962149, Moran: 22107423, Planck: 27281024, Engine: parlia}\n\nNumber: 29020050\nHash: 0x975da225aa3b6b89d5640dc952b8c0a691471def59592c135d244ea6e741b400\n\t 0: cumulative: 139837 gas: 139837 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x2d7044607aecc15db6de3fd52047b471eca59e700458a391859da3245f676c1c logs: [0xc0ea993130 0xc0ea993290 0xc0ea993340 0xc0ea9933f0 0xc0ea9934a0] bloom: 00200200000000000000000080000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000200000000000000000000000000008000000200000100000000000000400000000000000000020000000020000000000000000000000000000000000000010041000000000000800000004000000000000000000240000000000080000004000000000020000000000000000000000020000000000000000000000000000000000000000001002000000000000000000000000000000000000001000000000000080000010000000000000010000000000000000000400000000000000000000004000 state: \n\t 1: cumulative: 160837 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x4320e093d2d6e70fb12708237ffa80a4323efa80ad6b7a3f640273d2b9d514f1 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: \n\t 2: cumulative: 181837 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x7b78a22fdc29df35f53623b9b71a328afe8827404b68a45c484c1c7291c45955 logs:

**Comment by jeremfrs** [comment]
Hello, i am stuck on block 29020049 aswell. Have you resolved the issue ? @arialix

**Comment by du5** [comment]
https://github.com/bnb-chain/bsc/releases/tag/v1.2.5

**Comment by du5** [comment]
hardfork upgrade named Luban at block height [29,020,050](https://bscscan.com/block/countdown/29020050).

**Comment by jeremfrs** [comment]
I just saw that, it works now. Thank you for the quick reply.

**Comment by arialix** [comment]
Big Thanks for ping @du5  . It works now

**Comment by seb-zhu** [comment]
Thank you so much. The nodes on my side are running out of disk space, the pruning operation is taking too long, it seems faster to re-use the snapshot. Can you tell me how long it will take to recover, thank you

**Comment by du5** [comment]
> Thank you so much. The nodes on my side are running out of disk space, the pruning operation is taking too long, it seems faster to re-use the snapshot. Can you tell me how long it will take to recover, thank you

hetzner can't give me exact time.

**Comment by du5** [comment]
> Thank you so much. The nodes on my side are running out of disk space, the pruning operation is taking too long, it seems faster to re-use the snapshot. Can you tell me how long it will take to recover, thank you

https://github.com/48Club/bsc-snapshots/commit/83e8916c8c7adac8019ea123247ea00c0164c304
