### ISSUE TITLE
Get full node snapshot cannot return old blocks or transactions

### ISSUE THREAD

**Issue by quickchase** [48Club/bsc-snapshots#81]
Geth fast node says it has `--pruneancient=true` but Geth full node does not. Geth full node also has `--txlookuplimit=0`

Thus, my assumption would be that the Geth full node snapshot would not prune old blocks, transactions, receipts, etc., and that this should work:

```json
{"jsonrpc":"2.0","id":1,"method":"eth_getBlockByNumber","params":["0x3d0900",false]}
```

However, it returns `null` - so I am confused about the flags that this snapshot was running and why this doesn't work.

Additionally, trying to get old transactions doesn't work either, despite `--txlookuplimit=0`

```json
{"jsonrpc":"2.0","id":1,"method":"eth_getTransactionByHash","params":["0xa0f2e87dfb75e3ebb8b23eff7b490442ff74cf8921eb61217dfc48918fe4020f"]}
```

I downloaded the latest snapshot yesterday:
```
https://snapshots.48.club/geth.fast.30043191.tar.zst (Jul-17-2023 01:41:09 PM +UTC)
```

**Comment by du5** [comment]
We prune before packing. This reduces the size of the database, which means historical data is inaccessible


https://github.com/bnb-chain/bsc/pull/728

**Comment by quickchase** [comment]
Then what exactly is the point of this snapshot vs the fast snapshot? Those flags are meaningless and misleading.

**Comment by du5** [comment]
https://github.com/bnb-chain/bsc/pull/728

**Comment by quickchase** [comment]
That doesn't answer the question.

**Comment by quickchase** [comment]
So really the full snapshot is a Fast Full Node and not actually a Full node snapshot. Why not just say that?

**Comment by du5** [comment]
Please don't confuse full with archive

`
local: a normal full node with complete state world(both MPT and snapshot), merkle state root will be verified against the block header.
`

**Comment by du5** [comment]
After full node prune, you will not be able to query the data before prune, geth has always been like this

**Comment by du5** [comment]
Similarly, you can also find a recent snapshot without prune to solve the problem

https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230719.tar.lz4

**Comment by quickchase** [comment]
In what world is asking for blocks (not state, just the blocks) confusing Full vs Archive?

Geth has not always been like this. Maybe BSC's fork of geth has always been like this but I can ask ANY geth node on any other network for headers, blocks, receipts, and transactions (assuming txlookuplimit=0 is set) just fine.

That includes all other forks of geth

Celo, go-opera, Avalanchego, Bor, etc.

Nobody calls this full except BSC

But, ok
