### ISSUE TITLE
EOF from server 

### ISSUE THREAD

**Issue by edjiH** [48Club/bsc-snapshots#83]
Hi, i am getting the following error while trying to download the full node geth snapshot  with aria2c and was wondering if this was on my side or yours Thanks in advance .
08/02 17:59:47 [^[[1;31mERROR^[[0m] CUID#9 - Download aborted. URI=https://snapshots.48.club/geth.full.30389515.tar.zst
Exception: [DownloadCommand.cc:234] errorCode=1 Got EOF from the server.

08/02 17:59:47 [^[[1;32mNOTICE^[[0m] Download GID#c2555591f12e5418 not complete: /home/geth.full.30389515.tar.zst

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
c25555|ERR |    76MiB/s|/home/geth.full.30389515.tar.zst

Status Legend:
(ERR):error occurred.

**Comment by du5** [comment]
try add flags `--disable-ipv6 `
