### ISSUE TITLE
Estimation of next erigon archive node release?

### ISSUE THREAD

**Issue by wtdcode** [48Club/bsc-snapshots#85]
The current release seems outdated (2 weeks old), any estimation of next release?

btw, how much storage does an archive node need at this moment? It is possible to fit into a 2*4T raid0 array (`df -h` says `7.3T`)?

**Comment by du5** [comment]
soon~  D8

**Comment by du5** [comment]
Encountered some problems during the sync process, we are waiting for the node-real team to follow up.


link https://github.com/node-real/bsc-erigon/issues/197
