### ISSUE TITLE
[2/15 Headers] No block headers to write in this log period block number=30499999

### ISSUE THREAD

**Issue by trugard** [48Club/bsc-snapshots#87]
Using erigon 1.1.7 found at the node-real/bsc-erigon project.
Using the archive snapshot. then moving the chaindata/mdbx.dat file to my actual chaindata folder. Although I have not moved parlia or the snapshots files from the extraction to my live chaindata folder (should I be using those as well?)

Keep getting a no block headers to write message.

On one attempt got a message to unwind ~48K blocks, the on the next attempt got a message to unwind ~97K blocks.

Node will start and write block bodies, but always gets stuck at writing headers.

Trying to determine if this is an issue with the snapshot or the client.

Attached a log snippet where I tells me to unwind.... siting the nonce is too low

[WARN] [08-15|05:37:31.680] [7/15 Execution] Execution failed block=30452142 hash=0xa490bba96f53f5abc3ce4b7dade68f12370593884eb9f9e443e24ae794c65b24 err="could not apply tx 0 from block 30452142 [0x9f9b00370b44881b9ca87293c1c9ce9fd311875c4e179e0771902997a5304f2b]: nonce too low: address 0x1865b71742f623AC09f1E999A4b2E939Df3Da4AB, tx: 61939 state: 275811"
[INFO] [08-15|05:37:31.680] UnwindTo block=30452141 bad_block_hash=0xa490bba96f53f5abc3ce4b7dade68f12370593884eb9f9e443e24ae794c65b24
[INFO] [08-15|05:37:31.682] [7/15 Execution] Completed on block=30452141
[INFO] [08-15|05:37:41.108] [2/15 Headers] Waiting for headers... from=30452141
[INFO] [08-15|05:37:47.711] [p2p] GoodPeers eth66=18 eth67=13
[INFO] [08-15|05:38:01.108] [2/15 Headers] No block headers to write in this log period block number=30452141

**Comment by du5** [comment]
please give feedback to [bsc](https://github.com/node-real/bsc-erigon/issues/new)
