### ISSUE TITLE
Decoding error (36) : Corrupted block detected

### ISSUE THREAD

**Issue by zhy827827** [48Club/bsc-snapshots#88]
https://snapshots.48.club/geth.full.30778710.tar.zst

$ zstd -d geth.full.30778710.tar.zst
```
ull.30778710.tar.zst : 532327 MB...     ull.30778710.tar.zst : Decoding error (36) : Corrupted block detected
```

Can officials repair these problems? What is the significance of such a snapshot?

**Comment by zhy827827** [comment]
@du5  快照解压不了

**Comment by du5** [comment]
check sha256sum first

**Comment by zhy827827** [comment]
The sha256sum value is right

**Comment by du5** [comment]
After testing the snapshot can be decompressed normally
