### ISSUE TITLE
Nonce Too Low

### ISSUE THREAD

**Issue by tpalaz** [48Club/bsc-snapshots#97]
Blocks 29,500,000 - 30,000,000 + appear to be corrupt. 

Running "debug_traceTransaction " or "debug_traceBlock" return the error:

`failed: nonce too high: address 0xeeD3EF2BA1797AeEF04be6bbEbd5BeD0Cb7f8528, tx: 3567779 state: 22634"}`

This problem only appeared after using snapshots. Issues can be seen:

- https://github.com/node-real/bsc-erigon/issues/205#issuecomment-1698647165
- (https://github.com/node-real/bsc-erigon/issues/199)

All have BNB48 snapshot

**Comment by du5** [comment]
Please provide the request data where the problem occurred and I will test it later.

**Comment by tpalaz** [comment]
> Please provide the request data where the problem occurred and I will test it later.


Following TX's with `traceTransaction`: 
`
0x3a4ff95a0a89b74ba989fa1ba90edab6c18b16709205702f2778dc35eff5a0e5
0xfb678bfdcd581f6ac2064df80d8d0e629ba0775ed1a87d0edb430f6d170a5113
0xabd260b521ed066460fd22f4d144b8ee7aa6fc7d3958cc7efc705dd6685b0128
0x064f4adfd670597da6540f4d0690223a3b7dcc527b12d1c4719dfe94c7b74b70
0x6867068db34c3888bd33adba275a2e73005f2f529b83953cf7fc1ee89e9fa34e
0xd3395b9d41988c0c4b27c984843fdff96d60f1908ba15abc02e9571093d61a32
0xb8b0688f9c35d2924613b417ef6fe233184407976a13e18b750ffa71d74e6810
0x74bf277f491d31610bcfa6fa116d59b24c7bdb64a271eb147654fa8c1dd70f90
0xf25f34426faf1cfe844671d3c00c3a3e0b92721f8cc1992a4c5556001e7fb526
0xe982631e2f15a4524491fc685889f6c39d00f973a33283d04fca4bd295d4a8ac
0xc3890d0fed602170dbca0a282f9f6455f1da2968e31d8f7088b3eedc0a3f86e6
0x0d84d7cfd41dd7c77c0241d648d3f0dba538c215e997819ffac78b975d20d36b
0x8de25226036ff4bab1adf3ff30f8c04211abec8467d0562ced7f135e741ed154
0xd6bac0062ee10908e277a42451c39a40d965f7e837049420f9c35afe0f8431dd
0xe6d9392de18dee5aaf07769cc9ea47b8fc355d006ecc2b5c5a5874e71920d05c
0x73efff9f80602b7a165f85ebff90ccd824da406b34e530ec0a5fcf4fe594b254
0x245e1521e1418a26438ca37502a0b7aaa3a8ffd92a40ed99eef9edf106386a33
0xfc1c891f898e03bac4c3d86209e2b79853ab44f5a76790639af08589f377322b
0x35fb12129333715cb7e58f1b8a2e7ae5c1667adc03a4f21bdf90ec1c9ce24aec
`

For blocks:
`
30821096
31302048
`

Some of these transactions/blocks may work. It seems everyone's nodes have different states where some TX's / blocks will trace and others will not.

**Comment by du5** [comment]
Most of the faulty blocks are after the snapshot we released. This is a problem that occurs during synchronization, not in the snapshot. see https://github.com/node-real/bsc-erigon/issues/199#issuecomment-1701991534

**Comment by du5** [comment]
However, I will still test it later

**Comment by tpalaz** [comment]
I figured this much, just wanted to bring to attention here incase it was snapshot error. 

Will close :)

**Comment by du5** [comment]
```
ubuntu-2204-jammy-64-minimal-hwe:/go# cat ~/.local/share/erigon/debug.sh 
traceTransaction="0x3a4ff95a0a89b74ba989fa1ba90edab6c18b16709205702f2778dc35eff5a0e5
0xfb678bfdcd581f6ac2064df80d8d0e629ba0775ed1a87d0edb430f6d170a5113
0xabd260b521ed066460fd22f4d144b8ee7aa6fc7d3958cc7efc705dd6685b0128
0x064f4adfd670597da6540f4d0690223a3b7dcc527b12d1c4719dfe94c7b74b70
0x6867068db34c3888bd33adba275a2e73005f2f529b83953cf7fc1ee89e9fa34e
0xd3395b9d41988c0c4b27c984843fdff96d60f1908ba15abc02e9571093d61a32
0xb8b0688f9c35d2924613b417ef6fe233184407976a13e18b750ffa71d74e6810
0x74bf277f491d31610bcfa6fa116d59b24c7bdb64a271eb147654fa8c1dd70f90
0xf25f34426faf1cfe844671d3c00c3a3e0b92721f8cc1992a4c5556001e7fb526
0xe982631e2f15a4524491fc685889f6c39d00f973a33283d04fca4bd295d4a8ac
0xc3890d0fed602170dbca0a282f9f6455f1da2968e31d8f7088b3eedc0a3f86e6
0x0d84d7cfd41dd7c77c0241d648d3f0dba538c215e997819ffac78b975d20d36b
0x8de25226036ff4bab1adf3ff30f8c04211abec8467d0562ced7f135e741ed154
0xd6bac0062ee10908e277a42451c39a40d965f7e837049420f9c35afe0f8431dd
0xe6d9392de18dee5aaf07769cc9ea47b8fc355d006ecc2b5c5a5874e71920d05c
0x73efff9f80602b7a165f85ebff90ccd824da406b34e530ec0a5fcf4fe594b254
0x245e1521e1418a26438ca37502a0b7aaa3a8ffd92a40ed99eef9edf106386a33
0xfc1c891f898e03bac4c3d86209e2b79853ab44f5a76790639af08589f377322b
0x35fb12129333715cb7e58f1b8a2e7ae5c1667adc03a4f21bdf90ec1c9ce24aec"

for i in $traceTransaction; do
    echo "Trace transaction $i"
    curl -s -X POST --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["'$i'",{"tracer":"prestateTracer"}],"id":1}' -H "Content-Type: application/json" localhost:8999
done


traceBlock="30821096
31302048"

for i in $traceBlock; do
    i=$(printf "%x" $i)
    echo "Trace block $i"
    curl -s -X POST --data '{"jsonrpc":"2.0","method":"debug_traceBlockByNumber","params":["0x'$i'",{"tracer":"callTracer"}],"id":1}' -H "Content-Type: application/json" localhost:8999 | jq 
done
ubuntu-2204-jammy-64-minimal-hwe:/go# bash ~/.local/share/erigon/debug.sh &>> ~/.local/share/erigon/debug.log
ubuntu-2204-jammy-64-minimal-hwe:/go# 
```


[debug.log](https://github.com/48Club/bsc-snapshots/files/12503251/debug.log)
